import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    height: "100%",
  },
  modalView: {
    width: "80%",
    height: "30%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 13,
    flexDirection: "column",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    borderWidth: 1.7,
    borderColor: "#3e3e3e",
  },

  line: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
    marginBottom: 20,
  },
  title: {
    textAlign: "center",
    fontSize: 23,
    color: "#3E3E3E",
  },
  pinInputContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  pinInput: {
    borderWidth: 1,
    borderColor: "#3e3e3e",
    borderRadius: 10,
    width: 40,
    height: 40,
    textAlign: "center",
    fontSize: 20,
    color: "#3E3E3E",
    marginHorizontal: 3,
  },

  biometricsContainer: {
    display: "flex",
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
  },

  actionText: {
    fontSize: 13,
  },
  actionButton: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "black",
    borderWidth: 1,
  },
  buttonText: {
    color: "black",
    fontSize: 12,
    textTransform: "uppercase",
  },

  buttonCloseContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 90,
    width: "100%",
    height: 80,
  },
  buttonCloseText: {
    color: "white",
    fontSize: 12,
    textTransform: "uppercase",
  },
  buttonClose: {
    display: "flex",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 13,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#3e3e3e",
    backgroundColor: "#3e3e3e",
    borderWidth: 1,
    width: "100%",
  },

  saveBttnLine: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "98%",
    marginBottom: 5,
    marginTop: 7,
  },
  buttonSave: {
    display: "flex",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#3e3e3e",
    backgroundColor: "#3e3e3e",
    borderWidth: 1,
    width: "100%",
  },
  buttonSaveText: {
    color: "white",
    fontSize: 12,
    textTransform: "uppercase",
  },

  cancelBttnLine: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "98%",
    marginBottom: 20,
  },
  buttonCancel: {
    display: "flex",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#3e3e3e",
    borderWidth: 1,
    width: "100%",
  },
  buttonCancelText: {
    color: "#3E3E3E",
    fontSize: 12,
    textTransform: "uppercase",
  },
});
