import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#3e3e3e",
    borderBottomEndRadius: 25,
    borderBottomStartRadius: 25,
  },
  settingsConfig: {
    backgroundColor: "white",
    paddingTop: 10,
    alignItems: "center",
  },
  lineContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "90%",
  },
  iconTextContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  text: {
    color: "#3E3E3E",
    fontSize: 16,
    marginLeft: 10,
  },
  actionButton: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#3e3e3e",
    borderWidth: 1,
  },
  actionButton2: {
    paddingHorizontal: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    color: "#3E3E3E",
    fontSize: 12,
    textTransform: "uppercase",
  },
  buttonCloseContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  buttonCloseText: {
    color: "#3e3e3e",
    fontSize: 12,
    textTransform: "uppercase",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalView: {
    width: "90%",
    height: "80%",
    backgroundColor: "#3e3e3e",
    borderRadius: 25,
    // padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalContainer: {
    display: "flex",
    backgroundColor: "white",
    height: "90%",
    width: "100%",
    borderRadius: 25,
    padding: 15,
  },
  headerModalContainer: {
    display: "flex",
    height: 70,
    width: "100%",
    marginLeft: 30,
    marginTop: 20,
  },
  separator: {
    borderWidth: 0.5,
    borderColor: "white",
    width: "90%",
    alignSelf: "center",
    marginBottom: 12,
    marginRight: 30,
  },
  buttonClose: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#3e3e3e",
    borderWidth: 1,
    width: "100%",
  },
  headerText: {
    color: "white",
    fontSize: 40,
  },
  listItemContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: "#e2e2e2",
  },
  studentConfigContainer: {
    backgroundColor: "#333",
    width: "100%",
    padding: 10,
    marginHorizontal: 10,
  },
  studentConfigHeader: {
    color: "white",
    fontSize: 16,
    marginBottom: 10,
  },
  studentInfoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  studentName: {
    color: "white",
    fontSize: 16,
  },
  switchStudentButton: {
    borderColor: "#FF6900",
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  switchStudentButtonText: {
    color: "white",
  },
});
